<?php

namespace Jupiter\IdcBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicoRepository extends EntityRepository
{
}
